/// this database is constructed base on response from APIs 
/// => name of fields of objects doesn't changed when integrating real APIs 
///Note : some fields is OPTIONAL , it can be not existed in API responses 
///     => Need check to display or not component which use fields
export const sample_db={
     data_bank:{
          round1:[
               {
                    metadata:{
                         id:'',
                         category:'',
                         code:'',
                         score:'',
                    },
                    questions:[
                         {
                              id:'',
                              content:'',
                              answers:[{
                                   id:'',
                                   content:'',
                                   is_correct:''
                              }],
                              image:''
                         }
                    ]
               }
          ],
          round2:[
               {
                    metadata:{
                         id:'',
                         keyword:{
                              content:'',
                              score:''
                         },
                         time:'',
                         score:'',
                    },
                    questions:[
                         {
                              id:'',
                              content:'',
                              answers:[{
                                   id:'',
                                   content:'',
                                   is_correct:''
                              }],
                              image:''
                         }
                    ],
                    hint_image:'',
               }
          ],
          round3:[
               {
                    metadata:{
                         id:'',
                         category:'',
                         code:'',
                         time:'',
                         score:'',
                    },
                    questions:[
                         {
                              id:'',
                              content:'',
                              answers:[{
                                   id:'',
                                   content:'',
                                   is_correct:''
                              }],
                              image:''
                         }
                    ]
               }
          ],
          round4:[
               {
                    metadata:{
                         id:'',
                         category:'',
                         code:'',
                         time:'',
                         score:'',
                    },
                    questions:[{
                         id:'',
                         content:'',
                         answers:[{
                              id:'',
                              content:'',
                              is_correct:''
                         }],
                         image:''
                    }]
               }
          ]
     },
}
