export const practiceActions={
    GET_PRACTICE_ROUNDS:'GET_PRACTICE_ROUNDS',
    ANSWER:'ANSWER',
    NEXT_ROUND:'NEXT_ROUND',
    CHOOSE_ROUND4_QUESTIONS:'CHOOSE_ROUND4_QUESTIONS',
    ANSWER_KEYWORD:'ANSWER_KEYWORD'
}

export const userActions={
    SIGNIN_SUCCESS:'SIGNIN_SUCCESS',
    SIGNOUT:'SIGNOUT'
}

